server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ajit
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_ON_EXIT=FALSE
    username: ajit
  jpa:
    hibernate:
      ddl-auto: update
      
      
planapi:
  message:
   planSaveSucc: Plan saved Succesfully
   planSaveFail: Plan Saved Fail
   planUpdateSucc: Plan Update Succesfully
   planUpdateFail: plan Update Fail
   PlanDeleteSucc: plan Deleted Succesfully
   planDeletefail: plan Deleted Succesfully
   planStatusChange: plan Status Change Succesfully
   planStatusChangFail: plan status change failed